name: fields
base: core20
version: 'v0.2.0'
summary: CLI tool for parsing columnar text
description: |
  fields is a tool for selecting columns of text. One or more individual columns
  and/or ranges of columns can be selected by index. Indexes can be positive
  (counting from the left) or negative (counting from the right). Ranges can
  bounded or unbounded (e.g. select all input to the left or right of N).

grade: stable
confinement: strict
architectures:
  - build-on: [amd64, arm64, armhf]

apps:
  fields:
    command: bin/fields

parts:
  fields:
    plugin: go
    go-channel: 1.16/stable
    source: https://github.com/shoenig/fields
    source-tag: v0.2.0
    source-type: git
    build-packages:
      - git
