name: fields
base: core18
version: 'v0.1.2'
summary: CLI tool for parsing columnar text
description: |
  fields is a tool for selecting columns of text. One or more individual columns
  and/or ranges of columns can be selected by index. Indexes can be positive
  (counting from the left) or negative (counting from the right). Ranges can
  bounded or unbounded (e.g. select all input to the left or right of N).

grade: stable
confinement: strict
architectures:
  - amd64

apps:
  fields:
    command: bin/fields

parts:
  fields:
    plugin: go
    go-channel: 1.13/stable
    source-tag: v0.1.2
    go-packages: [github.com/shoenig/fields/cmd/fields]
    build-packages:
      - git

