name: run-ci
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: true
          go-version: 1.18.1
      - name: Vet
        run: |
          go vet ./...
      - name: Tests
        run: |
          go test -race -v ./...

