name: run-ci
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-golang@v1
        with:
          version-file: go.mod
      - name: Vet
        run: |
          make vet
      - name: Tests
        run: |
          make test
  run-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-golang@v1
        with:
          version-file: go.mod
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.1
          skip-cache: true    
