name: run-ci
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-golang@v1
        with:
          version-file: go.mod
      - name: Vet
        run: |
          go vet ./...
      - name: Tests
        run: |
          go test -race -v ./...

